services:
  - type: web
    name: rotiseria-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    buildCommand: ''
    startCommand: ''
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: PORT
        value: 8000
    healthCheckPath: /docs
    internalPort: 8000
    autoDeploy: true
